databases:
  - name: sample_matchingApp_db_
    databaseName: sample_matching_app_db
    user: sample_matching_app_db_user
    region: singapore

services:
  - type: web
    name: sample_matching_app_db
    env: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/rails server"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: render_app
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false