default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 3
      processes: <%= (ENV["JOB_CONCURRENCY"] || 1) %>
      polling_interval: 0.1

production:
  workers:
    - queues:[active_storage*, mailers]
      threads: 3
      polling_interval: 5